location ^~ /api/ {
    alias /www/wwwroot/va.xruner.tk/server/public/;
    try_files $uri $uri/ /api/index.php$is_args$args;

    location ~ \.php$ {
        fastcgi_pass unix:/www/server/php/81/var/run/php-cgi-81.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_param SCRIPT_NAME /index.php;
    }

}

